### ISSUE TITLE
模块系统里面有一处不太正确

### ISSUE THREAD

**Issue by singpenguin** [photino/rust-notes#1]
创建一个lib, 如果写成src/chinese/greetings.rs编译会出错，应该写成mod.rs，rlib编译完后不太清楚应该怎样引用，是写在toml里面吗

**Comment by photino** [comment]
如果是创建了`src/chinese/greetings.rs`文件，应该在`src/chinese/mod.rs`文件中使用`pub mod greetings;`、在`src/lib.rs`中使用`pub mod chinese;`来导入。Rust中处理依赖是通过`toml`来实现的，使用`extern crate phrases;`来引用。

**Comment by singpenguin** [comment]
嗯，看了好久发现mod.rs和python中的**init**.py作用类似, use关键字其实就是from ... import ...

**Comment by photino** [comment]
对 同样也可以使用`as`关键词重命名
