### ISSUE TITLE
请问可否把您的笔记内容加入到 rustprimer（社区协作的书）里面？

### ISSUE THREAD

**Issue by Naupio** [photino/rust-notes#2]
Zan Pan 您好：

我是 [rust中文社区](https://github.com/rustcc) 的 大N，我们社区协作写了一本 [RustPrimer](https://github.com/rustcc/RustPrimer) 的书，我们看到您写的 rust-notes 很不错，我们想编辑部分内容加入的 rustprimer 里面，当然我们会著名是引用了您的笔记。我们写的书采用的是 CC4 知识共享协议，目的是在中国推广 Rust 和写一本新手友好的中文 Rust 书。并且希望您能参与到 rustprimer（2016.3.31 完成了初稿，还需要迭代润色修改） 的更新迭代当中。

祝您工作愉快，身体健康！

大N——rustcc/rustchina

**Comment by photino** [comment]
@Naupio 随便引用，这个Notes也是采用CC协议发布的。我今天刚通过This Week in Rust的推送了解到RustPrimer这本书，还没来得及开始仔细看，如果我发现有需要改的地方，会发起Issues或者PR。祝好！
